### PR TITLE
AlwaysOnTop => AlwaysOnTopOfFFXI

### PR DESCRIPTION
**Pull request by kyau**
References #24 
* Modified: changed AlwaysOnTop to only be always on top of `pol.exe` instead of using TopMost[^1]

[^1]: The methodology was pulled from a [stackoverflow post](https://stackoverflow.com/questions/45901631/is-it-possible-to-keep-a-form-on-top-of-another-but-not-topmost).

I assume this could also be expanded upon for use with private servers, such that you could specify the `.exe` to look for if it were to differ from `pol.exe`.

Two known issues with this method:
* When coming from AlwaysOnTopOfFFXI mode back to regular mode, the window is not shown in the taskbar until you double-click on the system tray icon. I am sure however that there is likely a work around for this as well.
* I am unsure how this would apply to multiple FINAL FANTASY XI instances running on the same machine as I cannot test this configuration myself. Could probably use the same method that is used to list the instances and select the one Mappy uses in order to pick the one that the window gets parented to as well, this would solve this issue.

To further the discussion here, I would also love to investigate reading from FFXI memory whether or not the game is in a cutscene/zoning and then hiding the map window accordingly.

### CODE REVIEW

**Comment by kyau** [comment]
So I was playing around a bit more to try and solve the second issue listed above. I tried to tie it directly into `this.Process` which references `m_game.Process`, however this caused more issues than it solved (causes Mappy to fail to find/load the maps). You might know more than me but I am pretty sure that tying it into this somehow will solve the multiple instance issue.

**Comment by KenshiDRK** [comment]
Can you explain this? "When coming from AlwaysOnTopOfFFXI mode back to regular mode, the window is not shown in the taskbar until you double-click on the system tray icon. I am sure however that there is likely a work around for this as well."
I tested and it all looks normal to me.

**Comment by KenshiDRK** [comment]
anyway it won't work when using several instances of the game, it should be docked to the game instance instead of the process, I'll also like to keep also the previous behavior and add this one.

**Comment by kyau** [comment]
> Can you explain this? "When coming from AlwaysOnTopOfFFXI mode back to regular mode, the window is not shown in the taskbar until you double-click on the system tray icon. I am sure however that there is likely a work around for this as well." I tested and it all looks normal to me.

It is possible it is something that happens that is specific to my setup, but what I mean is:

Normally an open app has an icon on the taskbar denoting that the application is open, Mappy for me usually has this. That is until I use this new parenting mode, then the only way I can see it open is either looking at the FFXI window or in the system tray (which while in that mode seems like normal behavior). The weird part comes when I right-click the map to remove the always on top (new parenting mode), it does not bring back this icon on the taskbar when doing so. However if I double-click on the system tray icon, almost as if to tell windows "re-open this from system tray" despite the fact that the window is obviously already shown, it will be shown again. I've attached a picture with the icon I am talking about circled in pink.

CWtWgeVCTs

I am going to assume, if this is an actual issue, that this just needs some sort of Windows (refresh the taskbar) call or something to fix. Meaning likely the fix is easy.

> anyway it won't work when using several instances of the game, it should be docked to the game instance instead of the process, I'll also like to keep also the previous behavior and add this one.

This I completely agree with, but I could not figure out in my limited time messing with the code how to go about doing this without breaking everything. I can look into this more unless you know how to go about it already, any assistance or nudge in the right direction would be appreciated.

**Comment by KenshiDRK** [comment]
Can you try this exe? 
[mappy.zip](https://github.com/KenshiDRK/mappy--Kenshi-Version/files/10682348/mappy.zip)

**Comment by kyau** [comment]
Does it with this version as well, this is a screenshot of directly after I first turned on `Docked to FFXI` then turned off `Always On Top` then I turned off `Docked to FFXI`. As noted above you will see there is no Mappy on my start menu. The moment after that screen shot was taken though, since I accessed the system tray menu of Mappy it was then shown. I am just thinking that if this is actually a bug this might confuse people leading the the window disappearing on them.

first image was chopped up to fit...

before
before
after
after

**Comment by KenshiDRK** [comment]
I think I solved it now. Can you test?
[mappy.zip](https://github.com/KenshiDRK/mappy--Kenshi-Version/files/10685773/mappy.zip)

**Comment by kyau** [comment]
While this fixed what I was talking about this now brings up another feature/bug, depending on how you look at it. Did you want it to always be in the taskbar, even when in `Docked to FFXI` mode? What happens now is the moment I switch into `Docked to FFXI` it disappears from the taskbar, only to reappear again once I click on the actual map or utilize the system tray icon in any way.

**Comment by KenshiDRK** [comment]
went with a different aproach and I think I have all solved, let me know how it works.
[mappy.zip](https://github.com/KenshiDRK/mappy--Kenshi-Version/files/10694152/mappy.zip)

**Comment by kyau** [comment]
This version works as expected. Enabling either `Always On Top` or `Docked to FFXI` or both and then disabling said option(s) now properly retains the now correctly titled icon on the taskbar `Mappy`. :+1:

**Comment by KenshiDRK** [comment]
Nice, I'll update it with what I have.

**Pull request closed without merging**
